language: 
  java
before_script: 
  mvn clean install -f systematic-trading-parent/pom.xml 
sudo: 
  false
script:
  mvn verify -B
addons:
  sonarcloud:
    organization: "Systematic-Trading" # the key of the org you chose at step #3
    token:
      secure: f0d14f9e0cd14afd133b69b43acd309298533e33 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar